### ISSUE TITLE
Enable PATCH requests in updateRelation Call

### ISSUE THREAD

**Issue by Jmeyering** [Jmeyering/hal-explorer#4]

**Comment by ureimers** [comment]
Yep, that would be nice! Currently we're dealing with a HAL-API that allows to PATCH single fields instead of PUTing entirely updated objects.

We're using `$this->followLink("patch", $response, $id, $options)` so far but having a dedicated method for that would be a lot cleaner.

But still thanks for this very tidy and small HAL client!

**Comment by Jmeyering** [comment]
Thanks for the kind words!

Just added the `patchUpdateRelation` method for you to use.

**Comment by ureimers** [comment]
That was fast, thank you!
